export const config = ({ config }) => config
export const configurations = ({ configurations }) => configurations
export const paymentServ = ({ paymentServ }) => paymentServ
export const chat = ({ chat }) => chat
export const menucfg = ({ menucfg }) => menucfg
export const rates = ({ rates }) => rates
export const menuDispType = ({ menuDispType }) => menuDispType
export const themecfg = ({ themecfg }) => themecfg
export const manifest = ({ manifest }) => manifest
export const leftDrawerOp = ({ leftDrawerOp }) => leftDrawerOp
export const leftDrawerCatOp = ({ leftDrawerCatOp }) => leftDrawerCatOp
export const searchBarState = ({ searchBarState }) => searchBarState
